name: spectral_lib_matcher
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - pip:
      - matchms >= 0.16.0
      - ms2deepscore >= 0.2.3
      - pytest
      - pytest-runner
      - spec2vec >= 0.6.0
      - tqdm
  - python >=3.7.*
  - requests
