name: spectral_lib_matcher
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - matchms >= 0.18.0
  - pandas
  - pip
  - pip:
      - ms2deepscore >= 0.3.0
      - pytest
      - pytest-runner
      - spec2vec >= 0.6.0
      - tqdm
  - python >=3.7.*
  - requests
