name: spectral_lib_matcher
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - pip:
      - matchms <= 0.14.0
      - pytest
      - pytest-runner
      - tqdm
  - python <= 3.9.7
  - requests
