name: spectral_lib_matcher
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - gensim
  - h5py
  - numpy
  - matchms >= 0.21.2
  - pandas
  - pip
  - pip:
      - ms2deepscore >= 0.4.0
      - pytest
      - pytest-runner
      - spec2vec >= 0.8.0
      - tqdm
  - python >=3.7
  - requests
