name: spectral_lib_matcher
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - gensim >= 4.3.3
  - h5py >= 3.12.1
  - numpy >=1.26.4
  - matchms >= 0.27.0
  - pandas >=2.2.3
  - pip
  - pip:
      - ms2deepscore >= 2.5.0
      - pytest >=8.3.4
      - pytest-runner >=6.0.1
      - spec2vec >= 0.8.0
      - tqdm >=4.67.1
  - python >=3.11
  - requests >=2.32.3
